### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by rayman89** [SEVENNetworks/AdClear#32]
Many apps still display ads even with the advanced protection on for example "Japanese talking translator". I have followed all the instructions to get the vpn etc but still displays ads.

**Comment by csandlin1** [comment]
Hello,

Thanks for contacting us. Sometimes your mileage may vary when it comes to AdClear. We just released a version into Beta testing that has improved our ad blocking for more phones. Try it here: https://betas.to/st7txDFq

**Comment by rayman89** [comment]
Got the same result with the beta.

**Comment by SEVENNetworks** [comment]
We are sorry you are still seeing ads and are going to take a closer look into the issue.  As soon as we have a resolution we will let you know so you can confirm whether or not the issue has been resolved.  Please let us know if there is anything else we can help you with.  We apologize for the delayed response.

Thanks for using AdClear!
